### ISSUE TITLE
Rename User to Member

### ISSUE THREAD

**Issue by AdityaSripal** [foranetworks/protocol#2]
I think the term `Member` captures the idea of `User` better, and it has less of a conceptual clash with the term `Client` from the ActivityPub context.

Different sets of clients from different ActivityPub servers may be members of the same Fora community

makes a lot more sense than

Different sets of clients from different ActivityPub servers may be users of the same Fora community

**Comment by 96RadhikaJadhav** [comment]
@AdityaSripal  Can I work on the issue?

**Comment by AdityaSripal** [comment]
Yes! @96RadhikaJadhav

**Comment by 96RadhikaJadhav** [comment]
@AdityaSripal  One doubt here. There are around 87 instances of the word user/s in all the 4 markdown files (core.md, dogma.md, goals.md, README.md) in the project. Should all those instances of the user be replaced with member? If not, then please specify the file where exactly it needs to be replaced.

**Comment by AdityaSripal** [comment]
Could you create a PR replacing all instances? If there is something that needs to stay as `User` I will comment to change it back

**Comment by AdityaSripal** [comment]
Closed by #7
